#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Sigmeh.Model;

namespace Sigmeh.Model	
{
	public partial class Area
	{
		private int _areaID;
		public virtual int AreaID
		{
			get
			{
				return this._areaID;
			}
			set
			{
				this._areaID = value;
			}
		}
		
		private string _url;
		public virtual string Url
		{
			get
			{
				return this._url;
			}
			set
			{
				this._url = value;
			}
		}
		
		private int? _areaMaeID;
		public virtual int? AreaMaeID
		{
			get
			{
				return this._areaMaeID;
			}
			set
			{
				this._areaMaeID = value;
			}
		}
		
		private bool _inativo;
		public virtual bool Inativo
		{
			get
			{
				return this._inativo;
			}
			set
			{
				this._inativo = value;
			}
		}
		
		private Area _area1;
		public virtual Area Area1
		{
			get
			{
				return this._area1;
			}
			set
			{
				this._area1 = value;
			}
		}
		
		private IList<Area> _areas = new List<Area>();
		public virtual IList<Area> Areas
		{
			get
			{
				return this._areas;
			}
		}
		
		private IList<Perfil> _perfils = new List<Perfil>();
		public virtual IList<Perfil> Perfils
		{
			get
			{
				return this._perfils;
			}
		}
		
	}
}
#pragma warning restore 1591
