#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Sigmeh.Model;

namespace Sigmeh.Model	
{
	public partial class Bairro
	{
		private int _bairroID;
		public virtual int BairroID
		{
			get
			{
				return this._bairroID;
			}
			set
			{
				this._bairroID = value;
			}
		}
		
		private int _cidadeID;
		public virtual int CidadeID
		{
			get
			{
				return this._cidadeID;
			}
			set
			{
				this._cidadeID = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private Cidade _cidade;
		public virtual Cidade Cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				this._cidade = value;
			}
		}
		
		private IList<Logradouro> _logradouros = new List<Logradouro>();
		public virtual IList<Logradouro> Logradouros
		{
			get
			{
				return this._logradouros;
			}
		}
		
		private IList<Logradouro> _logradouros1 = new List<Logradouro>();
		public virtual IList<Logradouro> Logradouros1
		{
			get
			{
				return this._logradouros1;
			}
		}
		
	}
}
#pragma warning restore 1591
