#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Sigmeh.Model;

namespace Sigmeh.Model	
{
	public partial class Endereco
	{
		private int _entidadeID;
		public virtual int EntidadeID
		{
			get
			{
				return this._entidadeID;
			}
			set
			{
				this._entidadeID = value;
			}
		}
		
		private int _enderecoID;
		public virtual int EnderecoID
		{
			get
			{
				return this._enderecoID;
			}
			set
			{
				this._enderecoID = value;
			}
		}
		
		private int _enderecoTipoID;
		public virtual int EnderecoTipoID
		{
			get
			{
				return this._enderecoTipoID;
			}
			set
			{
				this._enderecoTipoID = value;
			}
		}
		
		private string _cep;
		public virtual string Cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				this._cep = value;
			}
		}
		
		private string _logradouro;
		public virtual string Logradouro
		{
			get
			{
				return this._logradouro;
			}
			set
			{
				this._logradouro = value;
			}
		}
		
		private string _complemento;
		public virtual string Complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				this._complemento = value;
			}
		}
		
		private int? _numero;
		public virtual int? Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private string _observacao;
		public virtual string Observacao
		{
			get
			{
				return this._observacao;
			}
			set
			{
				this._observacao = value;
			}
		}
		
		private DateTime _dataCriacao;
		public virtual DateTime DataCriacao
		{
			get
			{
				return this._dataCriacao;
			}
			set
			{
				this._dataCriacao = value;
			}
		}
		
		private int _usuarioCriadorID;
		public virtual int UsuarioCriadorID
		{
			get
			{
				return this._usuarioCriadorID;
			}
			set
			{
				this._usuarioCriadorID = value;
			}
		}
		
		private DateTime _dataModificacao;
		public virtual DateTime DataModificacao
		{
			get
			{
				return this._dataModificacao;
			}
			set
			{
				this._dataModificacao = value;
			}
		}
		
		private int _usuarioModificadorID;
		public virtual int UsuarioModificadorID
		{
			get
			{
				return this._usuarioModificadorID;
			}
			set
			{
				this._usuarioModificadorID = value;
			}
		}
		
		private string _bairro;
		public virtual string Bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				this._bairro = value;
			}
		}
		
		private bool _isPrincipal;
		public virtual bool IsPrincipal
		{
			get
			{
				return this._isPrincipal;
			}
			set
			{
				this._isPrincipal = value;
			}
		}
		
		private int _cidadeID;
		public virtual int CidadeID
		{
			get
			{
				return this._cidadeID;
			}
			set
			{
				this._cidadeID = value;
			}
		}
		
		private EnderecoTipo _enderecoTipo;
		public virtual EnderecoTipo EnderecoTipo
		{
			get
			{
				return this._enderecoTipo;
			}
			set
			{
				this._enderecoTipo = value;
			}
		}
		
		private Entidade _entidade;
		public virtual Entidade Entidade
		{
			get
			{
				return this._entidade;
			}
			set
			{
				this._entidade = value;
			}
		}
		
		private Entidade _entidade1;
		public virtual Entidade Entidade1
		{
			get
			{
				return this._entidade1;
			}
			set
			{
				this._entidade1 = value;
			}
		}
		
		private Entidade _entidade2;
		public virtual Entidade Entidade2
		{
			get
			{
				return this._entidade2;
			}
			set
			{
				this._entidade2 = value;
			}
		}
		
		private Cidade _cidade;
		public virtual Cidade Cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				this._cidade = value;
			}
		}
		
	}
}
#pragma warning restore 1591
