#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Sigmeh.Model;

namespace Sigmeh.Model	
{
	public partial class Entidade
	{
		private int _entidadeID;
		public virtual int EntidadeID
		{
			get
			{
				return this._entidadeID;
			}
			set
			{
				this._entidadeID = value;
			}
		}
		
		private Guid _rowguid;
		public virtual Guid Rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				this._rowguid = value;
			}
		}
		
		private DateTime _dataCriacao;
		public virtual DateTime DataCriacao
		{
			get
			{
				return this._dataCriacao;
			}
			set
			{
				this._dataCriacao = value;
			}
		}
		
		private int _usuarioCriadorID;
		public virtual int UsuarioCriadorID
		{
			get
			{
				return this._usuarioCriadorID;
			}
			set
			{
				this._usuarioCriadorID = value;
			}
		}
		
		private bool _inativo;
		public virtual bool Inativo
		{
			get
			{
				return this._inativo;
			}
			set
			{
				this._inativo = value;
			}
		}
		
		private int _usuarioModificadorID;
		public virtual int UsuarioModificadorID
		{
			get
			{
				return this._usuarioModificadorID;
			}
			set
			{
				this._usuarioModificadorID = value;
			}
		}
		
		private string _tipoPessoa;
		public virtual string TipoPessoa
		{
			get
			{
				return this._tipoPessoa;
			}
			set
			{
				this._tipoPessoa = value;
			}
		}
		
		private string _rG;
		public virtual string RG
		{
			get
			{
				return this._rG;
			}
			set
			{
				this._rG = value;
			}
		}
		
		private string _observacao;
		public virtual string Observacao
		{
			get
			{
				return this._observacao;
			}
			set
			{
				this._observacao = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private int _entidadeTipoID;
		public virtual int EntidadeTipoID
		{
			get
			{
				return this._entidadeTipoID;
			}
			set
			{
				this._entidadeTipoID = value;
			}
		}
		
		private DateTime? _dataNascimento;
		public virtual DateTime? DataNascimento
		{
			get
			{
				return this._dataNascimento;
			}
			set
			{
				this._dataNascimento = value;
			}
		}
		
		private DateTime _dataModificacao;
		public virtual DateTime DataModificacao
		{
			get
			{
				return this._dataModificacao;
			}
			set
			{
				this._dataModificacao = value;
			}
		}
		
		private string _cPF;
		public virtual string CPF
		{
			get
			{
				return this._cPF;
			}
			set
			{
				this._cPF = value;
			}
		}
		
		private string _cNPJ;
		public virtual string CNPJ
		{
			get
			{
				return this._cNPJ;
			}
			set
			{
				this._cNPJ = value;
			}
		}
		
		private string _apelido;
		public virtual string Apelido
		{
			get
			{
				return this._apelido;
			}
			set
			{
				this._apelido = value;
			}
		}
		
		private Entidade _entidade1;
		public virtual Entidade Entidade1
		{
			get
			{
				return this._entidade1;
			}
			set
			{
				this._entidade1 = value;
			}
		}
		
		private EntidadeTipo _entidadeTipo;
		public virtual EntidadeTipo EntidadeTipo
		{
			get
			{
				return this._entidadeTipo;
			}
			set
			{
				this._entidadeTipo = value;
			}
		}
		
		private Entidade _entidade2;
		public virtual Entidade Entidade2
		{
			get
			{
				return this._entidade2;
			}
			set
			{
				this._entidade2 = value;
			}
		}
		
		private IList<Entidade> _entidades1 = new List<Entidade>();
		public virtual IList<Entidade> EntidadesRelacaoPai
		{
			get
			{
				return this._entidades1;
			}
		}
		
		private IList<Entidade> _entidades = new List<Entidade>();
		public virtual IList<Entidade> Entidades
		{
			get
			{
				return this._entidades;
			}
		}
		
		private IList<EnderecoTipo> _enderecoTipos = new List<EnderecoTipo>();
		public virtual IList<EnderecoTipo> EnderecoTipos
		{
			get
			{
				return this._enderecoTipos;
			}
		}
		
		private IList<EnderecoTipo> _enderecoTipos1 = new List<EnderecoTipo>();
		public virtual IList<EnderecoTipo> EnderecoTipos1
		{
			get
			{
				return this._enderecoTipos1;
			}
		}
		
		private IList<Endereco> _enderecos = new List<Endereco>();
		public virtual IList<Endereco> Enderecos
		{
			get
			{
				return this._enderecos;
			}
		}
		
		private IList<Endereco> _enderecos1 = new List<Endereco>();
		public virtual IList<Endereco> Enderecos1
		{
			get
			{
				return this._enderecos1;
			}
		}
		
		private IList<Endereco> _enderecos2 = new List<Endereco>();
		public virtual IList<Endereco> Enderecos2
		{
			get
			{
				return this._enderecos2;
			}
		}
		
		private IList<CanalComunicacaoTipo> _canalComunicacaoTipos = new List<CanalComunicacaoTipo>();
		public virtual IList<CanalComunicacaoTipo> CanalComunicacaoTipos
		{
			get
			{
				return this._canalComunicacaoTipos;
			}
		}
		
		private IList<CanalComunicacaoTipo> _canalComunicacaoTipos1 = new List<CanalComunicacaoTipo>();
		public virtual IList<CanalComunicacaoTipo> CanalComunicacaoTipos1
		{
			get
			{
				return this._canalComunicacaoTipos1;
			}
		}
		
		private IList<CanalComunicacao> _canalComunicacaos = new List<CanalComunicacao>();
		public virtual IList<CanalComunicacao> CanalComunicacaos
		{
			get
			{
				return this._canalComunicacaos;
			}
		}
		
		private IList<CanalComunicacao> _canalComunicacaos1 = new List<CanalComunicacao>();
		public virtual IList<CanalComunicacao> CanalComunicacaos1
		{
			get
			{
				return this._canalComunicacaos1;
			}
		}
		
		private IList<CanalComunicacao> _canalComunicacaos2 = new List<CanalComunicacao>();
		public virtual IList<CanalComunicacao> CanalComunicacaos2
		{
			get
			{
				return this._canalComunicacaos2;
			}
		}
		
		private IList<EntidadeTipo> _entidadeTipos = new List<EntidadeTipo>();
		public virtual IList<EntidadeTipo> EntidadeTipos
		{
			get
			{
				return this._entidadeTipos;
			}
		}
		
		private IList<EntidadeTipo> _entidadeTipos1 = new List<EntidadeTipo>();
		public virtual IList<EntidadeTipo> EntidadeTipos1
		{
			get
			{
				return this._entidadeTipos1;
			}
		}
		
		private IList<RegistroManutencao> _registroManutencaos = new List<RegistroManutencao>();
		public virtual IList<RegistroManutencao> RegistroManutencaos
		{
			get
			{
				return this._registroManutencaos;
			}
		}
		
		private IList<Telefone> _telefones = new List<Telefone>();
		public virtual IList<Telefone> Telefones
		{
			get
			{
				return this._telefones;
			}
		}
		
		private IList<Telefone> _telefones1 = new List<Telefone>();
		public virtual IList<Telefone> Telefones1
		{
			get
			{
				return this._telefones1;
			}
		}
		
		private IList<Telefone> _telefones2 = new List<Telefone>();
		public virtual IList<Telefone> Telefones2
		{
			get
			{
				return this._telefones2;
			}
		}
		
		private IList<TelefoneTipo> _telefoneTipos = new List<TelefoneTipo>();
		public virtual IList<TelefoneTipo> TelefoneTipos
		{
			get
			{
				return this._telefoneTipos;
			}
		}
		
		private IList<TelefoneTipo> _telefoneTipos1 = new List<TelefoneTipo>();
		public virtual IList<TelefoneTipo> TelefoneTipos1
		{
			get
			{
				return this._telefoneTipos1;
			}
		}
		
		private IList<Equipamento> _equipamentos = new List<Equipamento>();
		public virtual IList<Equipamento> Equipamentos
		{
			get
			{
				return this._equipamentos;
			}
		}
		
		private IList<ManutencaoTipo> _manutencaoTipos = new List<ManutencaoTipo>();
		public virtual IList<ManutencaoTipo> ManutencaoTipos
		{
			get
			{
				return this._manutencaoTipos;
			}
		}
		
		private IList<ManutencaoTipo> _manutencaoTipos1 = new List<ManutencaoTipo>();
		public virtual IList<ManutencaoTipo> ManutencaoTipos1
		{
			get
			{
				return this._manutencaoTipos1;
			}
		}
		
		private IList<ManutencaoStatus> _manutencaoStatus = new List<ManutencaoStatus>();
		public virtual IList<ManutencaoStatus> ManutencaoStatus
		{
			get
			{
				return this._manutencaoStatus;
			}
		}
		
		private IList<ManutencaoStatus> _manutencaoStatus1 = new List<ManutencaoStatus>();
		public virtual IList<ManutencaoStatus> ManutencaoStatus1
		{
			get
			{
				return this._manutencaoStatus1;
			}
		}
		
		private IList<EquipamentoTipo> _equipamentoTipos = new List<EquipamentoTipo>();
		public virtual IList<EquipamentoTipo> EquipamentoTipos
		{
			get
			{
				return this._equipamentoTipos;
			}
		}
		
		private IList<EquipamentoTipo> _equipamentoTipos1 = new List<EquipamentoTipo>();
		public virtual IList<EquipamentoTipo> EquipamentoTipos1
		{
			get
			{
				return this._equipamentoTipos1;
			}
		}
		
		private IList<Periodicidade> _periodicidades = new List<Periodicidade>();
		public virtual IList<Periodicidade> Periodicidades
		{
			get
			{
				return this._periodicidades;
			}
		}
		
		private IList<Periodicidade> _periodicidades1 = new List<Periodicidade>();
		public virtual IList<Periodicidade> Periodicidades1
		{
			get
			{
				return this._periodicidades1;
			}
		}
		
		private IList<ItemManutencao> _itemManutencaos = new List<ItemManutencao>();
		public virtual IList<ItemManutencao> ItemManutencaos
		{
			get
			{
				return this._itemManutencaos;
			}
		}
		
		private IList<ItemManutencao> _itemManutencaos1 = new List<ItemManutencao>();
		public virtual IList<ItemManutencao> ItemManutencaos1
		{
			get
			{
				return this._itemManutencaos1;
			}
		}
		
		private IList<Entidade> _entidades11 = new List<Entidade>();
		public virtual IList<Entidade> EntidadesRelacaoFilho
		{
			get
			{
				return this._entidades11;
			}
		}
		
		private IList<Equipamento> _equipamentos1 = new List<Equipamento>();
		public virtual IList<Equipamento> Equipamentos1
		{
			get
			{
				return this._equipamentos1;
			}
		}
		
		private IList<Equipamento> _equipamentos2 = new List<Equipamento>();
		public virtual IList<Equipamento> Equipamentos2
		{
			get
			{
				return this._equipamentos2;
			}
		}
		
		private IList<RegistroManutencao> _registroManutencaos1 = new List<RegistroManutencao>();
		public virtual IList<RegistroManutencao> RegistroManutencaos1
		{
			get
			{
				return this._registroManutencaos1;
			}
		}
		
		private IList<RegistroManutencao> _registroManutencaos2 = new List<RegistroManutencao>();
		public virtual IList<RegistroManutencao> RegistroManutencaos2
		{
			get
			{
				return this._registroManutencaos2;
			}
		}
		
		private IList<RegistroManutencao> _registroManutencaos3 = new List<RegistroManutencao>();
		public virtual IList<RegistroManutencao> RegistroManutencaos3
		{
			get
			{
				return this._registroManutencaos3;
			}
		}
		
		private IList<Entidade> _entidades12 = new List<Entidade>();
		public virtual IList<Entidade> Entidades1
		{
			get
			{
				return this._entidades12;
			}
		}
		
		private Usuario _usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
