#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Sigmeh.Model;

namespace Sigmeh.Model	
{
	public partial class Equipamento
	{
		private int _equipamentoID;
		public virtual int EquipamentoID
		{
			get
			{
				return this._equipamentoID;
			}
			set
			{
				this._equipamentoID = value;
			}
		}
		
		private Guid _rowguid;
		public virtual Guid Rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				this._rowguid = value;
			}
		}
		
		private DateTime _dataCriacao;
		public virtual DateTime DataCriacao
		{
			get
			{
				return this._dataCriacao;
			}
			set
			{
				this._dataCriacao = value;
			}
		}
		
		private int _usuarioCriadorID;
		public virtual int UsuarioCriadorID
		{
			get
			{
				return this._usuarioCriadorID;
			}
			set
			{
				this._usuarioCriadorID = value;
			}
		}
		
		private bool _inativo;
		public virtual bool Inativo
		{
			get
			{
				return this._inativo;
			}
			set
			{
				this._inativo = value;
			}
		}
		
		private int _usuarioModificadorID;
		public virtual int UsuarioModificadorID
		{
			get
			{
				return this._usuarioModificadorID;
			}
			set
			{
				this._usuarioModificadorID = value;
			}
		}
		
		private string _tag;
		public virtual string Tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				this._tag = value;
			}
		}
		
		private int? _periodicidadeQtdeDias;
		public virtual int? PeriodicidadeQtdeDias
		{
			get
			{
				return this._periodicidadeQtdeDias;
			}
			set
			{
				this._periodicidadeQtdeDias = value;
			}
		}
		
		private int _periodicidadeID;
		public virtual int PeriodicidadeID
		{
			get
			{
				return this._periodicidadeID;
			}
			set
			{
				this._periodicidadeID = value;
			}
		}
		
		private int _periodicidadeCalibracaoID;
		public virtual int PeriodicidadeCalibracaoID
		{
			get
			{
				return this._periodicidadeCalibracaoID;
			}
			set
			{
				this._periodicidadeCalibracaoID = value;
			}
		}
		
		private string _patrimonio;
		public virtual string Patrimonio
		{
			get
			{
				return this._patrimonio;
			}
			set
			{
				this._patrimonio = value;
			}
		}
		
		private string _numeroSerie;
		public virtual string NumeroSerie
		{
			get
			{
				return this._numeroSerie;
			}
			set
			{
				this._numeroSerie = value;
			}
		}
		
		private string _marca_Modelo;
		public virtual string Marca_Modelo
		{
			get
			{
				return this._marca_Modelo;
			}
			set
			{
				this._marca_Modelo = value;
			}
		}
		
		private string _localizacao;
		public virtual string Localizacao
		{
			get
			{
				return this._localizacao;
			}
			set
			{
				this._localizacao = value;
			}
		}
		
		private int _equipamentoTipoID;
		public virtual int EquipamentoTipoID
		{
			get
			{
				return this._equipamentoTipoID;
			}
			set
			{
				this._equipamentoTipoID = value;
			}
		}
		
		private int _empresaVinculadaID;
		public virtual int EmpresaVinculadaID
		{
			get
			{
				return this._empresaVinculadaID;
			}
			set
			{
				this._empresaVinculadaID = value;
			}
		}
		
		private string _descricao;
		public virtual string Descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				this._descricao = value;
			}
		}
		
		private DateTime _dataModificacao;
		public virtual DateTime DataModificacao
		{
			get
			{
				return this._dataModificacao;
			}
			set
			{
				this._dataModificacao = value;
			}
		}
		
		private string _acessorios;
		public virtual string Acessorios
		{
			get
			{
				return this._acessorios;
			}
			set
			{
				this._acessorios = value;
			}
		}
		
		private Entidade _entidade;
		public virtual Entidade Entidade
		{
			get
			{
				return this._entidade;
			}
			set
			{
				this._entidade = value;
			}
		}
		
		private Periodicidade _periodicidade;
		public virtual Periodicidade Periodicidade
		{
			get
			{
				return this._periodicidade;
			}
			set
			{
				this._periodicidade = value;
			}
		}
		
		private Periodicidade _periodicidade1;
		public virtual Periodicidade Periodicidade1
		{
			get
			{
				return this._periodicidade1;
			}
			set
			{
				this._periodicidade1 = value;
			}
		}
		
		private EquipamentoTipo _equipamentoTipo;
		public virtual EquipamentoTipo EquipamentoTipo
		{
			get
			{
				return this._equipamentoTipo;
			}
			set
			{
				this._equipamentoTipo = value;
			}
		}
		
		private Entidade _entidade1;
		public virtual Entidade Entidade1
		{
			get
			{
				return this._entidade1;
			}
			set
			{
				this._entidade1 = value;
			}
		}
		
		private Entidade _entidade2;
		public virtual Entidade Entidade2
		{
			get
			{
				return this._entidade2;
			}
			set
			{
				this._entidade2 = value;
			}
		}
		
		private IList<RegistroManutencao> _registroManutencaos = new List<RegistroManutencao>();
		public virtual IList<RegistroManutencao> RegistroManutencaos
		{
			get
			{
				return this._registroManutencaos;
			}
		}
		
	}
}
#pragma warning restore 1591
