#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Sigmeh.Model;

namespace Sigmeh.Model	
{
	public partial class ItemManutencao
	{
		private int _itemManutencaoID;
		public virtual int ItemManutencaoID
		{
			get
			{
				return this._itemManutencaoID;
			}
			set
			{
				this._itemManutencaoID = value;
			}
		}
		
		private int _registroManutencaoID;
		public virtual int RegistroManutencaoID
		{
			get
			{
				return this._registroManutencaoID;
			}
			set
			{
				this._registroManutencaoID = value;
			}
		}
		
		private string _descricao;
		public virtual string Descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				this._descricao = value;
			}
		}
		
		private decimal? _quantidade;
		public virtual decimal? Quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				this._quantidade = value;
			}
		}
		
		private string _lote;
		public virtual string Lote
		{
			get
			{
				return this._lote;
			}
			set
			{
				this._lote = value;
			}
		}
		
		private string _numeroSerie;
		public virtual string NumeroSerie
		{
			get
			{
				return this._numeroSerie;
			}
			set
			{
				this._numeroSerie = value;
			}
		}
		
		private decimal? _custo;
		public virtual decimal? Custo
		{
			get
			{
				return this._custo;
			}
			set
			{
				this._custo = value;
			}
		}
		
		private DateTime _dataCriacao;
		public virtual DateTime DataCriacao
		{
			get
			{
				return this._dataCriacao;
			}
			set
			{
				this._dataCriacao = value;
			}
		}
		
		private int _usuarioCriador;
		public virtual int UsuarioCriador
		{
			get
			{
				return this._usuarioCriador;
			}
			set
			{
				this._usuarioCriador = value;
			}
		}
		
		private DateTime _dataModificacao;
		public virtual DateTime DataModificacao
		{
			get
			{
				return this._dataModificacao;
			}
			set
			{
				this._dataModificacao = value;
			}
		}
		
		private int _usuarioModificador;
		public virtual int UsuarioModificador
		{
			get
			{
				return this._usuarioModificador;
			}
			set
			{
				this._usuarioModificador = value;
			}
		}
		
		private RegistroManutencao _registroManutencao;
		public virtual RegistroManutencao RegistroManutencao
		{
			get
			{
				return this._registroManutencao;
			}
			set
			{
				this._registroManutencao = value;
			}
		}
		
		private Entidade _entidade;
		public virtual Entidade Entidade
		{
			get
			{
				return this._entidade;
			}
			set
			{
				this._entidade = value;
			}
		}
		
		private Entidade _entidade1;
		public virtual Entidade Entidade1
		{
			get
			{
				return this._entidade1;
			}
			set
			{
				this._entidade1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
