#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Sigmeh.Model;

namespace Sigmeh.Model	
{
	public partial class Pai
	{
		private int _paisID;
		public virtual int PaisID
		{
			get
			{
				return this._paisID;
			}
			set
			{
				this._paisID = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private short? _dDI;
		public virtual short? DDI
		{
			get
			{
				return this._dDI;
			}
			set
			{
				this._dDI = value;
			}
		}
		
		private IList<Estado> _estados = new List<Estado>();
		public virtual IList<Estado> Estados
		{
			get
			{
				return this._estados;
			}
		}
		
		private IList<Cidade> _cidades = new List<Cidade>();
		public virtual IList<Cidade> Cidades
		{
			get
			{
				return this._cidades;
			}
		}
		
	}
}
#pragma warning restore 1591
