#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Sigmeh.Model;

namespace Sigmeh.Model	
{
	public partial class RegistroManutencao
	{
		private int _registroManutencaoID;
		public virtual int RegistroManutencaoID
		{
			get
			{
				return this._registroManutencaoID;
			}
			set
			{
				this._registroManutencaoID = value;
			}
		}
		
		private Guid _rowguid;
		public virtual Guid Rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				this._rowguid = value;
			}
		}
		
		private DateTime _dataCriacao;
		public virtual DateTime DataCriacao
		{
			get
			{
				return this._dataCriacao;
			}
			set
			{
				this._dataCriacao = value;
			}
		}
		
		private int _usuarioCriadorID;
		public virtual int UsuarioCriadorID
		{
			get
			{
				return this._usuarioCriadorID;
			}
			set
			{
				this._usuarioCriadorID = value;
			}
		}
		
		private bool _excluido;
		public virtual bool Excluido
		{
			get
			{
				return this._excluido;
			}
			set
			{
				this._excluido = value;
			}
		}
		
		private int _usuarioModificadorID;
		public virtual int UsuarioModificadorID
		{
			get
			{
				return this._usuarioModificadorID;
			}
			set
			{
				this._usuarioModificadorID = value;
			}
		}
		
		private string _relatorioDescricao;
		public virtual string RelatorioDescricao
		{
			get
			{
				return this._relatorioDescricao;
			}
			set
			{
				this._relatorioDescricao = value;
			}
		}
		
		private int _manutencaoTipoID;
		public virtual int ManutencaoTipoID
		{
			get
			{
				return this._manutencaoTipoID;
			}
			set
			{
				this._manutencaoTipoID = value;
			}
		}
		
		private int _manutencaoStatusID;
		public virtual int ManutencaoStatusID
		{
			get
			{
				return this._manutencaoStatusID;
			}
			set
			{
				this._manutencaoStatusID = value;
			}
		}
		
		private int _executorID;
		public virtual int ExecutorID
		{
			get
			{
				return this._executorID;
			}
			set
			{
				this._executorID = value;
			}
		}
		
		private int _equipamentoID;
		public virtual int EquipamentoID
		{
			get
			{
				return this._equipamentoID;
			}
			set
			{
				this._equipamentoID = value;
			}
		}
		
		private string _defeitoDescricao;
		public virtual string DefeitoDescricao
		{
			get
			{
				return this._defeitoDescricao;
			}
			set
			{
				this._defeitoDescricao = value;
			}
		}
		
		private DateTime _dataRealizacao;
		public virtual DateTime DataRealizacao
		{
			get
			{
				return this._dataRealizacao;
			}
			set
			{
				this._dataRealizacao = value;
			}
		}
		
		private DateTime _dataModificacao;
		public virtual DateTime DataModificacao
		{
			get
			{
				return this._dataModificacao;
			}
			set
			{
				this._dataModificacao = value;
			}
		}
		
		private int _aprovadorID;
		public virtual int AprovadorID
		{
			get
			{
				return this._aprovadorID;
			}
			set
			{
				this._aprovadorID = value;
			}
		}
		
		private Entidade _entidade;
		public virtual Entidade Entidade
		{
			get
			{
				return this._entidade;
			}
			set
			{
				this._entidade = value;
			}
		}
		
		private ManutencaoTipo _manutencaoTipo;
		public virtual ManutencaoTipo ManutencaoTipo
		{
			get
			{
				return this._manutencaoTipo;
			}
			set
			{
				this._manutencaoTipo = value;
			}
		}
		
		private ManutencaoStatus _manutencaoStatus;
		public virtual ManutencaoStatus ManutencaoStatus
		{
			get
			{
				return this._manutencaoStatus;
			}
			set
			{
				this._manutencaoStatus = value;
			}
		}
		
		private Equipamento _equipamento;
		public virtual Equipamento Equipamento
		{
			get
			{
				return this._equipamento;
			}
			set
			{
				this._equipamento = value;
			}
		}
		
		private Entidade _entidade1;
		public virtual Entidade Entidade1
		{
			get
			{
				return this._entidade1;
			}
			set
			{
				this._entidade1 = value;
			}
		}
		
		private Entidade _entidade2;
		public virtual Entidade Entidade2
		{
			get
			{
				return this._entidade2;
			}
			set
			{
				this._entidade2 = value;
			}
		}
		
		private Entidade _entidade3;
		public virtual Entidade Entidade3
		{
			get
			{
				return this._entidade3;
			}
			set
			{
				this._entidade3 = value;
			}
		}
		
		private IList<ItemManutencao> _itemManutencaos = new List<ItemManutencao>();
		public virtual IList<ItemManutencao> ItemManutencaos
		{
			get
			{
				return this._itemManutencaos;
			}
		}
		
		private RegistroManutencaoArquivo _registroManutencaoArquivo;
		public virtual RegistroManutencaoArquivo RegistroManutencaoArquivo
		{
			get
			{
				return this._registroManutencaoArquivo;
			}
			set
			{
				this._registroManutencaoArquivo = value;
			}
		}
		
	}
}
#pragma warning restore 1591
