#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Sigmeh.Model;

namespace Sigmeh.Model	
{
	public partial class Usuario
	{
		private int _usuarioID;
		public virtual int UsuarioID
		{
			get
			{
				return this._usuarioID;
			}
			set
			{
				this._usuarioID = value;
			}
		}
		
		private string _login;
		public virtual string Login
		{
			get
			{
				return this._login;
			}
			set
			{
				this._login = value;
			}
		}
		
		private string _senha;
		public virtual string Senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				this._senha = value;
			}
		}
		
		private Entidade _entidade;
		public virtual Entidade Entidade
		{
			get
			{
				return this._entidade;
			}
			set
			{
				this._entidade = value;
			}
		}
		
		private IList<Perfil> _perfils = new List<Perfil>();
		public virtual IList<Perfil> Perfils
		{
			get
			{
				return this._perfils;
			}
		}
		
	}
}
#pragma warning restore 1591
