#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Sigmeh.Model	
{
	public partial class Vw_StatusSaidaEquipamento
	{
		private int _registroManutencaoID;
		public virtual int RegistroManutencaoID
		{
			get
			{
				return this._registroManutencaoID;
			}
			set
			{
				this._registroManutencaoID = value;
			}
		}
		
		private int _manutencaoTipoID;
		public virtual int ManutencaoTipoID
		{
			get
			{
				return this._manutencaoTipoID;
			}
			set
			{
				this._manutencaoTipoID = value;
			}
		}
		
		private int _equipamentoID;
		public virtual int EquipamentoID
		{
			get
			{
				return this._equipamentoID;
			}
			set
			{
				this._equipamentoID = value;
			}
		}
		
		private int _empresaVinculadaID;
		public virtual int EmpresaVinculadaID
		{
			get
			{
				return this._empresaVinculadaID;
			}
			set
			{
				this._empresaVinculadaID = value;
			}
		}
		
		private int? _diasPrazo;
		public virtual int? DiasPrazo
		{
			get
			{
				return this._diasPrazo;
			}
			set
			{
				this._diasPrazo = value;
			}
		}
		
		private DateTime _dataRealizacao;
		public virtual DateTime DataRealizacao
		{
			get
			{
				return this._dataRealizacao;
			}
			set
			{
				this._dataRealizacao = value;
			}
		}
		
		private DateTime? _dataPrevista;
		public virtual DateTime? DataPrevista
		{
			get
			{
				return this._dataPrevista;
			}
			set
			{
				this._dataPrevista = value;
			}
		}
		
	}
}
#pragma warning restore 1591
